App\Entity\CaObjects:
  shortName: 'Objects'                   # optional
  description: 'Physical objects in the collection'
  attributes:                          # optional
    pagination_items_per_page: 30   # optional
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']

App\Entity\CaEntities:
  shortName: 'People'                   # optional
  description: '(CaEntities) people (author, artist, etc.)'
  attributes:                          # optional
    pagination_items_per_page: 30   # optional
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']

